import React from 'react';
import styles from "./features.module.css";

const features = () => {
    return (
        <div className={styles.features_wrapper}>
            <div className={styles.cards}>


                <div className={styles.card}>
                    <div className={styles.img}><svg width="72" height="72" viewBox="0 0 72 72" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M54.6667 12H17.3333C14.3878 12 12 14.3878 12 17.3333V54.6667C12 57.6122 14.3878 60 17.3333 60H54.6667C57.6122 60 60 57.6122 60 54.6667V17.3333C60 14.3878 57.6122 12 54.6667 12Z" fill="#146EB4" fill-opacity="0.15" stroke="#146EB4" stroke-width="3.5" stroke-miterlimit="10" />
                        <path d="M12 28H60" stroke="#146EB4" stroke-width="3.5" stroke-miterlimit="10" />
                        <path d="M28 60V28" stroke="#146EB4" stroke-width="3.5" stroke-miterlimit="10" />
                    </svg>
                    </div>
                    <div className={styles.title}>Search</div>
                    <div className={styles.card_desc}>Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.</div>
                </div>

                <div className={styles.card}>
                    <div className={styles.img}><svg width="72" height="72" viewBox="0 0 72 72" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <g clip-path="url(#clip0_1_598)">
                            <rect x="8" y="12" width="56" height="48" rx="5" fill="#146EB4" fill-opacity="0.15" stroke="#146EB4" stroke-width="3.5" stroke-miterlimit="10" />
                            <path d="M26 27L34.3324 47L37.2905 38.2905L46 35.3324L26 27Z" stroke="#146EB4" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round" />
                        </g>
                        <defs>
                            <clipPath id="clip0_1_598">
                                <rect width="72" height="72" fill="white" />
                            </clipPath>
                        </defs>
                    </svg>

                    </div>
                    <div className={styles.title}>Select</div>
                    <div className={styles.card_desc}>Choose from thousands of options generated by the slogan maker that fit your needs.</div>
                </div>

                <div className={styles.card}>
                    <div className={styles.img}><svg width="72" height="72" viewBox="0 0 72 72" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M36 64C51.464 64 64 51.464 64 36C64 20.536 51.464 8 36 8C20.536 8 8 20.536 8 36C8 51.464 20.536 64 36 64Z" fill="#146EB4" fill-opacity="0.15" stroke="#146EB4" stroke-width="3.5" stroke-miterlimit="10" />
                        <path d="M44 31L36 23L28 31" stroke="#146EB4" stroke-width="3.2" stroke-linecap="round" stroke-linejoin="round" />
                        <path d="M36 23V42.2" stroke="#146EB4" stroke-width="3.2" stroke-linecap="round" stroke-linejoin="round" />
                        <path d="M54 40.2857L49.7143 36L45.4286 40.2857" stroke="#146EB4" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round" />
                        <path d="M49.7143 36V46.2857" stroke="#146EB4" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round" />
                        <path d="M26.5714 40.2857L22.2857 36L18 40.2857" stroke="#146EB4" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round" />
                        <path d="M22.2857 36V46.2857" stroke="#146EB4" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round" />
                    </svg>

                    </div>
                    <div className={styles.title}>Stand out</div>
                    <div className={styles.card_desc}>Congrats on your new slogan. It's time to win the world!</div>
                </div>
            </div>
        </div>
    )
}

export default features